config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'comments#index'
  get 'comments/index'
  get 'comments/main'
  resources :machings, only: [:create, :update, :show]
  resources :messages, only: [:create]
  resources :notifications, only: [:index]
  resources :menus, only: [:create,:destroy]
  resources :cards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    if current_user
    @request_user = current_user.request_users.eager_load(:reverse_of_machings).where(machings: { aggree: false })
    @requested_user = current_user.requested_users.eager_load(:machings).where(machings: { aggree: false })
    @approve_request_user = current_user.request_users.eager_load(:reverse_of_machings).where(machings: { aggree: true })
    @approve_requested_user  = current_user.requested_users.eager_load(:machings).where(machings: { aggree: true })
    @menu = Menu.new
    @menus = current_user.menus
    else
      redirect_to new_user_session_path
    end
  end

  def main
    @menus = Menu.search(params[:keyword])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/index.html.erb
<h1>ログインアプリ</h1>

<% if user_signed_in? %> <!-- ユーザーがログインしているか調べる -->
  <!-- ユーザーがログインしていた時の処理 -->
  <h2> 現在 <%= current_user.name %> さんがログインしています </h2> <!-- ここを追加します -->
  <%= flash[:alert] %>
  <% current_user.images.each do |image| %>
    <%= image_tag image %>
  <% end %>
  <h4> メールアドレス： <%= current_user.email %> </h4>
  <%= link_to "プロフィール編集",  edit_user_registration_path %>
  <%= link_to "ユーザー一覧", comments_main_path %>
  <%=  "依頼済みのユーザー"%>
  <% @request_user.each do |user| %>
    <%= user.name %>
  <% end %>
  <%= "依頼してきたユーザー" %>
  <% @requested_user.each do |user| %>
    <%= user.name %>
  <% end %>
  <%= "マッチング済みユーザー" %>
  <% @approve_requested_user.each do |user| %>
    <% user.machings.where(aggree: true, requested_user_id: current_user.id).each do |maching| %>
      <%= link_to "#{user.name}", maching_path(maching.id) %>
    <% end%>
  <%end%>
  <% @approve_request_user.each do |user| %>
    <% user.reverse_of_machings.where(aggree: true, request_user_id: current_user.id).each do |maching| %>
      <%= link_to "#{user.name}", maching_path(maching.id) %>
    <% end%>
  <%end%>
  <% if current_user.notifications.where(notification_read: false).present? %>
    <%= link_to "通知", notifications_path, style: 'color: red;' %>
    <span style = "color: red;"><%= current_user.notifications.where(notification_read: false).size %></span>
  <% else %>
    <%= link_to "通知", notifications_path %>
  <% end %>
  <%= form_with model: @menu, local: true do |f| %>
    <%= f.label :name, "メニュー名" %>
    <%= f.text_field :name %>
    <%= f.label :fee, "金額" %>
    <%= f.number_field :fee %>
    <%= f.submit "メニュー作成" %>
    <% @menu.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  <% @menus.each do |menu| %>
    <%= menu.name %>
    <%= menu.fee %>
    <%= "円" %>
    <%= link_to "削除", menu_path(id: menu.id), method: :delete %>
  <% end %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %> <!-- ログアウトをする -->
<% else %>
  <!-- ユーザーがログインしていなかった時の処理 -->
  <h2> 現在ログインしていません </h2>
  <%= link_to "ログイン", new_user_session_path, class: 'post' %> <!-- ログイン画面に移行する -->
  <%= link_to "新規登録", new_user_registration_path, class: 'post' %> <!-- 新規登録画面に移行する -->
<% end %>

app/views/comments/main.html.erb
<h1>ユーザー一覧</h1>

<% if user_signed_in? %> <!-- ユーザーがログインしているか調べる -->
  <!-- ユーザーがログインしていた時の処理 -->
  <%# <% @users.each do |user| %>
  <p>メニュー検索</p>
  <%= form_with(url: comments_main_path, method: :get, local: true) do |f|%>
    <%= f.text_field :keyword %>
    <%= f.submit 'Search' %>
  <% end %>
  <% if @menus.blank? %>
  <p>検索結果が見つかりませんでした</p>
  <% end %>
  <% @menus.each do |menu| %>
    <% user = menu.user %>
    <% if user.flag != current_user.flag %>
      <% if user == current_user %>
      <%# 自分を非表示にする %>
      <% else %>
        <% if flash[:success] %>
          <%= flash[:success] %>
        <% elsif flash[:alert] %>
          <%= flash[:alert] %>
        <% end %>
        <% user.images.each do |image| %>
          <%= image_tag image %>
        <% end %>
        <h4> 名前： <%= user.name %> </h4>
        <h4> メールアドレス： <%= user.email %> </h4>  
        <% user.menus.each do |menu| %>
          <%= menu.name %>
          <%= menu.fee %>
          <%= "円" %>
        <% end%>
        <%# 依頼ボタン %>
        <% if current_user.approving?(user) %>
          <% user.machings.where(aggree: true, requested_user_id: current_user.id).each do |maching| %>
              <%= link_to "承認済み DMへ", maching_path(maching.id) %>
          <% end%>
        <% elsif current_user.approved?(user) %>
          <% user.reverse_of_machings.where(aggree: true, request_user_id: current_user.id).each do |maching| %>
              <%= link_to "承認されました DMへ", maching_path(maching.id) %>
          <% end%>
        <% elsif current_user.requesting?(user) %>
          <%= "すでに依頼済みです" %>
        <% elsif current_user.requested?(user) %>
          <%= "依頼されています" %>
          <!-- maching_pathはルートで定義したmachings#updateのパスである -->
          <%= link_to "承認する", maching_path(current_user.reverse_of_machings.find_by(request_user_id: user.id)), method: :put %>
        <% else %>
          <%= render 'machings/request_button', user: user %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  <%= link_to "プロフィール", root_path %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %> <!-- ログアウトをする -->
<% else %>
  <!-- ユーザーがログインしていなかった時の処理 -->
  <h2> 現在ログインしていません </h2>
  <%= link_to "ログイン", new_user_session_path, class: 'post' %> <!-- ログイン画面に移行する -->
  <%= link_to "新規登録", new_user_registration_path, class: 'post' %> <!-- 新規登録画面に移行する -->
<% end %>